name: Auto Assign Reviewer and Assignee

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Assign reviewer and assignee
        uses: kentaro-m/auto-assign-action@v1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }} #Errors persist
          reviewers: bernarditoro # Assigns bernarditoro as the reviewer
          assignees: bernarditoro # Assigns bernarditoro as the assignee
