name: Auto-Assign Reviewer and Assignee

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewer and assignee
        uses: ahmadnassri/action-auto-assign@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: bernarditoro # Assigns bernarditoro as the reviewer
          assignees: bernarditoro # Assigns bernarditoro as the assignee
