name: Auto Assign Reviewer and Assignee

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Assign reviewers
        uses: actions/assign-reviewers@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: "reviewer1,reviewer2"
