# filepath: /Users/Peniel/Backends/sen211-e-learning-project/.github/workflows/assign.yml
name: Auto Assign Reviewer and Assignee

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Assign reviewer and assignee
        uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/auto_assign.yml